### ISSUE TITLE
Architecture - Object - UUID

### ISSUE THREAD

**Issue by LucasTesnier** [Cavonstavant/mes_equipes#25]
Implement all the my_UUID object function.

Add the following function : my_uuid_copy who does the following
- Create a new my_uuid object with the content of another

Add the following function : my_uuid_edit who does the following
- Change the value of the my_uuid passed in parameter

Add the following function : my_uuid_find who does the following
- Return the Index of the my_uuid passed in parameter when is find in the my_uuid list passed by parameter
- When no matching my_uuid is find, return -1

Constant : 
Add the following function : my_uuid_generate who does the following
- Generate a new my_uuid in terms of the Object type passed in parameter

**Comment by Cavonstavant** [comment]
List of prefixes:
| Prefix | Related Module |
|---------|-----------------------|
| TEM_ | Team UUID |
| CHA_ | Channel UUID |
| THR_ | Thread UUID |
| COM_ | Comment UUID |
| USR_ | User UUID |
| CON_ | Conversation UUID |
| DMS_ | Direct Message UUID |

**Comment by LucasTesnier** [comment]
Add wrapper destructor
